[package]
name = "rawflate"
version = "0.1.1"
edition = "2024"
rust-version = "1.89"

[[bin]]
name = "rawflate"
path = "src/main.rs"

[dependencies]
preflate-container = { git = "https://github.com/microsoft/preflate-rs", tag = "v0.7.6" }
lepton_jpeg = "0.5.1"
clap = { version = "4", features = ["derive"] }
